Звіт роботи ПІБ

In [3]:

import pandas as pd

   # Завантаження даних
df = pd.read_csv('operations_db.csv')

   # Перегляд перших рядків
print(df.head())
   
   # Огляд інформації про набір даних
print(df.info())

                       op_name  start_date  end_date  location_1 location_2  \
0      Operation Abilene, 1966    19660407  19660410   Phuoc Tuy        NaN
1  Operation Adairsville, 1968    19680131  19680308    Bien Hoa        NaN
2   Operation Adams, 1966-1967    19661026  19670330     Phu Yen        NaN
3        Operation Ahina, 1967    19670513  19670518  Binh Duong   Tay Ninh
4         Operation Aiea, 1966    19660808  19660901   Hau Nghia        NaN

  location_3 location_4
0        NaN        NaN
1        NaN        NaN
2        NaN        NaN
3        NaN        NaN
4        NaN        NaN
<class 'pandas.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   op_name     255 non-null    str
 1   start_date  255 non-null    int64
 2   end_date    255 non-null    int64
 3   location_1  255 non-null    str
 4   location_2  72 non-null     str
 5   location_3  20 non-null     str
 6   location_4  9 non-null      str
dtypes: int64(2), str(5)
memory usage: 14.1 KB
None

In [5]:
# 1. Перевірка пропущених значень
print("Кількість пропущених значень у кожному стовпці:")
print(df.isnull().sum())

Кількість пропущених значень у кожному стовпці:
op_name         0
start_date      0
end_date        0
location_1      0
location_2    183
location_3    235
location_4    246
dtype: int64

In [6]:
# 2. Заповнення пропущених значень

# Числові стовпці заповнюємо медіаною
numeric_columns = df.select_dtypes(include=["int64", "float64"]).columns

for column in numeric_columns:
    df[column] = df[column].fillna(df[column].median())

In [8]:
#3. Видалення дублікатів
df.drop_duplicates(inplace=True)

In [9]:
 #4 Перетворення категоріальних змінних на числові (якщо потрібно)
df['category_column'] = df['category_column'].astype('category').cat.codes

KeyError: 'category_column'

In [10]:
print(df.columns)

Index(['op_name', 'start_date', 'end_date', 'location_1', 'location_2',
       'location_3', 'location_4'],
      dtype='str')

In [11]:
print(df.select_dtypes(include=['object']).columns)

Index(['op_name', 'location_1', 'location_2', 'location_3', 'location_4'], dtype='str')

C:\Users\eve2026\AppData\Local\Temp\ipykernel_15452\845905018.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.select_dtypes(include=['object']).columns)

In [1]:
 # Перетворення категоріальних змінних на числові (якщо потрібно)
df['category_column'] = df['location_1'].astype('category').cat.codes

NameError: name 'df' is not defined

In [3]:
import pandas as pd

df = pd.read_csv(
    r'D:\НАВЧАННЯ\VS_Code\Practica\Thema_3\p3_3\operations_db.csv'
)

display(df.head())
print(df.columns.tolist())

ModuleNotFoundError: No module named 'pandas'

In [4]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.3-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lotos\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\lotos\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.8 MB 5.6 MB/s eta 0:00:02
   ------- -------------------------------- 1.8/9.8 MB 5.9 MB/s eta 0:00:02
   ------------ --------------------------- 3.1/9.8 MB 5.9 MB/s eta 0:00:02
   ------------------ --------------------- 4.5/9.8 MB 6.1 MB/s eta 0:00:01
   ----------------------- ---------------- 5.8/9.8 MB 6.2 MB/s eta 0:00:01
   --------------------------- ------------ 6.8/9.8 MB 6.3 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.8 MB 6.2 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 6.2 MB/s eta 0:00:00
Downloading numpy-2.5.3-cp312-cp312-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.6 MB 6.7 MB/s eta 0:00:02
   --------- ------------------------------ 2.9/12.6 MB 7.3 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.6 MB 7.3 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.6 MB 7.0 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.6 MB 6.6 MB/s eta 0:00:01
   --------------------- ------------------ 6.8/12.6 MB 5.7 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.6 MB 5.5 MB/s eta 0:00:01
   ------------------------- -------------- 7.9/12.6 MB 4.8 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.6 MB 4.8 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.6 MB 4.8 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.6 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 4.9 MB/s eta 0:00:00
Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.5.3 pandas-3.0.5 tzdata-2026.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

print(pd.__version__)

3.0.5

In [2]:
df['location_1'] = df['location_1'].astype('category').cat.codes

NameError: name 'df' is not defined

In [3]:
import pandas as pd

df = pd.read_csv('operations_db.csv')

display(df.head())
print(df.columns.tolist())

,op_name,start_date,end_date,location_1,location_2,location_3,location_4
0,"Operation Abilene, 1966",19660407,19660410,Phuoc Tuy,NaN,NaN,NaN
1,"Operation Adairsville, 1968",19680131,19680308,Bien Hoa,NaN,NaN,NaN
2,"Operation Adams, 1966-1967",19661026,19670330,Phu Yen,NaN,NaN,NaN
3,"Operation Ahina, 1967",19670513,19670518,Binh Duong,Tay Ninh,NaN,NaN
4,"Operation Aiea, 1966",19660808,19660901,Hau Nghia,NaN,NaN,NaN

['op_name', 'start_date', 'end_date', 'location_1', 'location_2', 'location_3', 'location_4']

In [4]:
df.columns = df.columns.str.strip()

df['location_1_code'] = (
    df['location_1']
    .astype('category')
    .cat.codes
)

display(df[['location_1', 'location_1_code']].head())

   location_1  location_1_code
0   Phuoc Tuy               35
1    Bien Hoa                0
2     Phu Yen               32
3  Binh Duong                3
4   Hau Nghia               18

5. **Описова статистика**:
   - Виконайте описову статистику для числових змінних.
   - Визначте основні показники: середнє значення, медіану, стандартне відхилення.

   **Код**:
   ```python
   # Описова статистика
   print(df.describe())
   ```

In [5]:
# Описова статистика
print(df.describe())

         start_date      end_date  location_1_code
count  2.550000e+02  2.550000e+02       255.000000
mean   1.967002e+07  1.966990e+07        24.329412
std    1.422130e+04  4.153515e+04        17.489967
min    1.964041e+07  1.907032e+07         0.000000
25%    1.966066e+07  1.966077e+07         3.500000
50%    1.967021e+07  1.967051e+07        25.000000
75%    1.968012e+07  1.968041e+07        41.000000
max    1.975050e+07  1.975050e+07        52.000000

count — кількість значень;
mean — середнє арифметичне;
std — стандартне відхилення;
min — мінімальне значення;
25% — перший квартиль;
50% — медіана;
75% — третій квартиль;
max — максимальне значення.

In [6]:
# Вибираємо лише числові стовпці
numeric_df = df.select_dtypes(include='number')

# Основні статистичні показники
statistics = pd.DataFrame({
    'Середнє значення': numeric_df.mean(),
    'Медіана': numeric_df.median(),
    'Стандартне відхилення': numeric_df.std()
})

display(statistics)

                 Середнє значення     Медіана  Стандартне відхилення
start_date           1.967002e+07  19670214.0           14221.298493
end_date             1.966990e+07  19670514.0           41535.146003
location_1_code      2.432941e+01        25.0              17.489967

In [7]:
# без стопчика, що перетворили на числовий
numeric_df = df.select_dtypes(include='number').drop(
    columns=['location_1_code'],
    errors='ignore'
)

statistics = pd.DataFrame({
    'Середнє значення': numeric_df.mean(),
    'Медіана': numeric_df.median(),
    'Стандартне відхилення': numeric_df.std()
})

display(statistics)

            Середнє значення     Медіана  Стандартне відхилення
start_date      1.967002e+07  19670214.0           14221.298493
end_date        1.966990e+07  19670514.0           41535.146003

**Візуалізація даних**:
   - Створіть кілька графіків для аналізу розподілу даних та виявлення взаємозв’язків.
   - Використовуйте Seaborn або Matplotlib для створення гістограм, коробкових діаграм (boxplot), діаграм розсіювання.

In [11]:
%pip install seaborn matplotlib

Requirement already satisfied: seaborn in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (0.13.2)
Requirement already satisfied: matplotlib in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (3.11.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (2.5.3)
Requirement already satisfied: pandas>=1.2 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=9 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lotos\appdata\roaming\python\python312\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.2->seaborn) (2026.4)
Requirement already satisfied: six>=1.5 in c:\users\lotos\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

ImportError: DLL load failed while importing _path: An Application Control policy has blocked this file.

In [2]:
%pip install --upgrade --force-reinstall numpy matplotlib seaborn

Collecting numpy
  Using cached numpy-2.5.3-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Collecting matplotlib
  Using cached matplotlib-3.11.2-cp312-cp312-win_amd64.whl.metadata (80 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.4.0-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Using cached fonttools-4.65.0-cp312-cp312-win_amd64.whl.metadata (127 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.5.1-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Collecting packaging>=20.0 (from matplotlib)
  Downloading packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.3.0-cp312-cp312-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting python-dateutil>=2.7 (from matplotlib)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pandas>=1.2 (from seaborn)
  Using cached pandas-3.0.5-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting tzdata (from pandas>=1.2->seaborn)
  Using cached tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.7->matplotlib)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached numpy-2.5.3-cp312-cp312-win_amd64.whl (12.6 MB)
Using cached matplotlib-3.11.2-cp312-cp312-win_amd64.whl (9.3 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached contourpy-1.4.0-cp312-cp312-win_amd64.whl (234 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.65.0-cp312-cp312-win_amd64.whl (2.5 MB)
Using cached kiwisolver-1.5.1-cp312-cp312-win_amd64.whl (70 kB)
Downloading packaging-26.3-py3-none-any.whl (129 kB)
Using cached pandas-3.0.5-cp312-cp312-win_amd64.whl (9.8 MB)
Downloading pillow-12.3.0-cp312-cp312-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   -------- ------------------------------- 1.6/7.2 MB 12.0 MB/s eta 0:00:01
   ------------------------ --------------- 4.5/7.2 MB 11.7 MB/s eta 0:00:01
   ------------------------------------ --- 6.6/7.2 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 11.1 MB/s eta 0:00:00
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached tzdata-2026.4-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, six, pyparsing, pillow, packaging, numpy, kiwisolver, fonttools, cycler, python-dateutil, contourpy, pandas, matplotlib, seaborn
  Attempting uninstall: tzdata
    Found existing installation: tzdata 2026.4
    Uninstalling tzdata-2026.4:
      Successfully uninstalled tzdata-2026.4
  Attempting uninstall: six
    Found existing installation: six 1.17.0
    Uninstalling six-1.17.0:
      Successfully uninstalled six-1.17.0
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 3.3.2
    Uninstalling pyparsing-3.3.2:
      Successfully uninstalled pyparsing-3.3.2
  Attempting uninstall: pillow
    Found existing installation: pillow 12.1.1
    Uninstalling pillow-12.1.1:
      Successfully uninstalled pillow-12.1.1
  Attempting uninstall: packaging
    Found existing installation: packaging 26.0
    Uninstalling packaging-26.0:
      Successfully uninstalled packaging-26.0
  Attempting uninstall: numpy
    Found existing installation: numpy 2.5.3
    Uninstalling numpy-2.5.3:
      Successfully uninstalled numpy-2.5.3
  Attempting uninstall: kiwisolver
    Found existing installation: kiwisolver 1.5.1
    Uninstalling kiwisolver-1.5.1:
      Successfully uninstalled kiwisolver-1.5.1
  Attempting uninstall: fonttools
    Found existing installation: fonttools 4.65.0
    Uninstalling fonttools-4.65.0:
      Successfully uninstalled fonttools-4.65.0
  Attempting uninstall: cycler
    Found existing installation: cycler 0.12.1
    Uninstalling cycler-0.12.1:
      Successfully uninstalled cycler-0.12.1
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
      Successfully uninstalled python-dateutil-2.9.0.post0
  Attempting uninstall: contourpy
    Found existing installation: contourpy 1.4.0
    Uninstalling contourpy-1.4.0:
      Successfully uninstalled contourpy-1.4.0
  Attempting uninstall: pandas
    Found existing installation: pandas 3.0.5
    Uninstalling pandas-3.0.5:
      Successfully uninstalled pandas-3.0.5
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.11.2
    Uninstalling matplotlib-3.11.2:
      Successfully uninstalled matplotlib-3.11.2
  Attempting uninstall: seaborn
    Found existing installation: seaborn 0.13.2
    Uninstalling seaborn-0.13.2:
      Successfully uninstalled seaborn-0.13.2
Successfully installed contourpy-1.4.0 cycler-0.12.1 fonttools-4.65.0 kiwisolver-1.5.1 matplotlib-3.11.2 numpy-2.5.3 packaging-26.3 pandas-3.0.5 pillow-12.3.0 pyparsing-3.3.2 python-dateutil-2.9.0.post0 seaborn-0.13.2 six-1.17.0 tzdata-2026.4
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\lotos\AppData\Local\Programs\Python\Python312\Lib\site-packages\~il'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\lotos\AppData\Local\Programs\Python\Python312\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\lotos\AppData\Local\Programs\Python\Python312\Lib\site-packages\~umpy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\lotos\AppData\Local\Programs\Python\Python312\Lib\site-packages\~andas'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\lotos\AppData\Local\Programs\Python\Python312\Lib\site-packages\~atplotlib'.
  You can safely remove it manually.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

print("Pandas:", pd.__version__)
print("Seaborn:", sns.__version__)

ImportError: DLL load failed while importing _path: An Application Control policy has blocked this file.

In [2]:
%pip uninstall matplotlib seaborn -y
%pip install matplotlib seaborn

Found existing installation: matplotlib 3.11.2
Uninstalling matplotlib-3.11.2:
  Successfully uninstalled matplotlib-3.11.2
Found existing installation: seaborn 0.13.2
Uninstalling seaborn-0.13.2:
  Successfully uninstalled seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

WARNING: Failed to remove contents in a temporary directory 'C:\Users\lotos\AppData\Local\Programs\Python\Python312\Lib\site-packages\~-tplotlib'.
You can safely remove it manually.

Collecting matplotlib
  Using cached matplotlib-3.11.2-cp312-cp312-win_amd64.whl.metadata (80 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: numpy>=1.25 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (2.5.3)
Requirement already satisfied: packaging>=20.0 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: tzdata in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.2->seaborn) (2026.4)
Requirement already satisfied: six>=1.5 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Using cached matplotlib-3.11.2-cp312-cp312-win_amd64.whl (9.3 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: matplotlib, seaborn
Successfully installed matplotlib-3.11.2 seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

print("Бібліотеки успішно підключено")

ImportError: DLL load failed while importing _path: An Application Control policy has blocked this file.

In [2]:
%pip install plotly nbformat

Collecting plotly
  Downloading plotly-7.0.0-py3-none-any.whl.metadata (8.7 kB)
Collecting nbformat
  Downloading nbformat-5.11.1-py3-none-any.whl.metadata (3.7 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Downloading narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: packaging in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from plotly) (26.3)
Collecting fastjsonschema>=2.15 (from nbformat)
  Downloading fastjsonschema-2.22.2-py3-none-any.whl.metadata (2.1 kB)
Collecting jsonschema>=2.6 (from nbformat)
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\lotos\appdata\roaming\python\python312\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\lotos\appdata\roaming\python\python312\site-packages (from nbformat) (5.16.1)
Collecting attrs>=22.2.0 (from jsonschema>=2.6->nbformat)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=2.6->nbformat)
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6->nbformat)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=2.6->nbformat)
  Downloading rpds_py-2026.6.3-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: platformdirs>=2.5 in c:\users\lotos\appdata\roaming\python\python312\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.11.2)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)
Downloading plotly-7.0.0-py3-none-any.whl (9.1 MB)
   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--
   ----- ---------------------------------- 1.3/9.1 MB 9.6 MB/s eta 0:00:01
   --------------- ------------------------ 3.4/9.1 MB 9.6 MB/s eta 0:00:01
   --------------------------- ------------ 6.3/9.1 MB 11.7 MB/s eta 0:00:01
   -------------------------------------- - 8.7/9.1 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------- 9.1/9.1 MB 11.5 MB/s eta 0:00:00
Downloading nbformat-5.11.1-py3-none-any.whl (79 kB)
Downloading fastjsonschema-2.22.2-py3-none-any.whl (27 kB)
Downloading jsonschema-4.26.0-py3-none-any.whl (90 kB)
Downloading narwhals-2.26.0-py3-none-any.whl (474 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Downloading referencing-0.37.0-py3-none-any.whl (26 kB)
Downloading rpds_py-2026.6.3-cp312-cp312-win_amd64.whl (220 kB)
Installing collected packages: rpds-py, narwhals, fastjsonschema, attrs, referencing, plotly, jsonschema-specifications, jsonschema, nbformat
Successfully installed attrs-26.1.0 fastjsonschema-2.22.2 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 narwhals-2.26.0 nbformat-5.11.1 plotly-7.0.0 referencing-0.37.0 rpds-py-2026.6.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import plotly.express as px

df = pd.read_csv('operations_db.csv')

print("Бібліотеки підключено")
print(df.columns.tolist())

Бібліотеки підключено
['op_name', 'start_date', 'end_date', 'location_1', 'location_2', 'location_3', 'location_4']

In [2]:
#Подивіться числові стовпці:
numeric_columns = df.select_dtypes(include='number').columns.tolist()
print(numeric_columns)

['start_date', 'end_date']

In [3]:
#Побудуйте гістограму автоматично для першого числового стовпця:

column = numeric_columns[0]

fig = px.histogram(
    df,
    x=column,
    nbins=20,
    title=f'Розподіл значень: {column}'
)

fig.show()

In [9]:
 # Коробкова діаграма для аналізу викидів
sns.boxplot(x=df['end_date'])
plt.show()

NameError: name 'sns' is not defined

In [10]:
#Спочатку перегляньте доступні числові стовпці:

print(df.select_dtypes(include='number').columns.tolist())

['start_date', 'end_date']

In [11]:
%pip install plotly

Requirement already satisfied: plotly in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (7.0.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from plotly) (2.26.0)
Requirement already satisfied: packaging in c:\users\lotos\appdata\local\programs\python\python312\lib\site-packages (from plotly) (26.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
import plotly.express as px

fig = px.box(
    df,
    y='end_date',
    points='outliers',
    title='Коробкова діаграма дат завершення операцій'
)

fig.show()

In [14]:
#Для одночасного порівняння start_date та end_date:

dates = df[['start_date', 'end_date']].melt(
    var_name='Тип дати',
    value_name='Значення'
)

fig = px.box(
    dates,
    x='Тип дати',
    y='Значення',
    points='outliers',
    title='Розподіл дат початку та завершення операцій'
)

fig.show()

In [ ]:
  # Діаграма розсіювання для двох кількісних змінних
sns.scatterplot(x=df['start_date'], y=df['end_date'])
plt.show()
# не виконується Помилка повторюється, тому що ви знову використовуєте sns.scatterplot(), але Seaborn у моїй системі не працює. Замініть цю клітинку повністю на код із Plotly:

NameError: name 'sns' is not defined

In [18]:
import plotly.express as px

fig = px.scatter(
    df,
    x='start_date',
    y='end_date',
    title='Залежність між датою початку та датою завершення',
    labels={
        'start_date': 'Дата початку',
        'end_date': 'Дата завершення'
    }
)

fig.show()

In [19]:
#Кореляційний аналіз**:
#   - Виконайте кореляційний аналіз для кількісних змінних.
#  - Виведіть кореляційну матрицю та проаналізуйте взаємозв’язки між змінними.

  
# Кореляційна матриця
correlation_matrix = df.corr()

ValueError: could not convert string to float: 'Operation Abilene, 1966'

In [20]:
# Вибираємо лише числові стовпці
numeric_df = df.select_dtypes(include='number')

# Обчислюємо кореляційну матрицю
correlation_matrix = numeric_df.corr()

display(correlation_matrix)

            start_date  end_date
start_date    1.000000  0.198733
end_date      0.198733  1.000000

In [21]:
correlation_matrix = df[['start_date', 'end_date']].corr()

display(correlation_matrix)

            start_date  end_date
start_date    1.000000  0.198733
end_date      0.198733  1.000000

In [22]:
import plotly.express as px

fig = px.imshow(
    correlation_matrix,
    text_auto='.2f',
    color_continuous_scale='RdBu_r',
    zmin=-1,
    zmax=1,
    title='Кореляційна матриця'
)

fig.show()

In [23]:
r = correlation_matrix.loc['start_date', 'end_date']

print(f'Коефіцієнт кореляції: {r:.2f}')

Коефіцієнт кореляції: 0.20

Орієнтовне тлумачення:

близько до 1 — сильний прямий зв’язок;
близько до −1 — сильний обернений зв’язок;
близько до 0 — лінійний зв’язок майже відсутній.



Проведено кореляційний аналіз числових змінних start_date та end_date. Отриманий коефіцієнт кореляції характеризує напрям і силу лінійного зв’язку між датами початку та завершення операцій. Водночас кореляція не доводить причинно-наслідкового зв’язку.

In [24]:
# Візуалізація кореляційної матриці по іншому
import plotly.express as px

# Вибір числових стовпців
numeric_df = df.select_dtypes(include='number')

# Розрахунок кореляцій
correlation_matrix = numeric_df.corr()

# Виведення таблиці
display(correlation_matrix)

# Візуалізація
fig = px.imshow(
    correlation_matrix,
    text_auto='.2f',
    color_continuous_scale='RdBu_r',
    zmin=-1,
    zmax=1,
    title='Кореляційна матриця'
)

fig.show()

            start_date  end_date
start_date    1.000000  0.198733
end_date      0.198733  1.000000